params ["_unitId"]; 
private _unit = AIO_monitor_array select _unitId;
AIO_monitoring_disabled = true;
sleep 0.1;
AIO_monitoring_enabled = true;
AIO_monitoring_disabled = false;
hintSilent formatText ["Press the %1 key again to exit", parseText "<t color='#FFFF00'>Menu"];
switchCamera _unit;
waitUntil {!alive _unit || AIO_monitoring_disabled};
switchCamera player;
AIO_monitoring_enabled = false;
sleep 1;
AIO_monitoring_disabled = false;